= Database (Destination) / Import Sheets
:last_updated: 6/29/2022
:author: Naomi
:linkattrs:
:experimental:
:page-layout: default-seekwell
:description: Now you can create or replace tables in your database based on a table in Google Sheets or another table in your database.

// destination

You can now create or replace tables in your database based on a table in Google Sheets or another table in your database. You can either use auto-import, or create a new block and set the Destination as "Database".

== Via Auto Import / Export

Auto import gives you a quick and simple option for importing tables in a Google Spreadsheet into your database. Watch the following video demonstration, or follow the steps below:

video::fzevbUCfVec[youtube]

. Go to the link:https://app.seekwell.io/[SeekWell Web App] and hit `cmd/ctrl` + `k`, then type "Import sheet to SQL Database".

. Click "Spreadsheet" and select your source Spreadsheet. If you don't see your source Spreadsheet in the drop-down menu, start typing its name or scroll to the bottom of the list and click "Refresh Sheets".

. Click "Destination" to select your destination database. You may need to add your database as a link:https://doc.seekwell.io/database-source[source], if you have not done so already.

. [Optional] Enter the table names you want your tables to be called to the right of their respective Sheets. By default, tables will be called their Sheet name. You can also uncheck any Sheets in the Spreadsheet that you don't want to import into your database. Then click "Import Sheets" on the bottom right.

. Double-check that your new table was successfully created.

NOTE: If you have gaps in your data (e.g. data in A:D, an empty column in E, and data F:G) then you will have to specify a range under the name of that Sheet.

== Via a New Block with Database as Destination

You can also create a new database table by creating a new block and setting the Destination as "Database". Watch the following demonstration video, or follow the steps below:

video::sq0kxgSUCWc[youtube]

. Start a new block in the link:https://app.seekwell.io/[SeekWell Web App] and choose the source of the data you want to create/replace a new table with. In this example, we use a table from Google Sheets as the source data, so we choose "Sheets/CSV/Block" as our source.

. Write SQL to fetch the data you want to use. If you want the entire table of your source data to be created/replaced in your destination database, simply `SELECT *` from your source table. If your source data is in a Google Sheet, remember to alias the Sheet in double curly braces, or `{{}}`, and change the xref:parameters.adoc[Parameter] Type to "Sheets". Then enter your correct Spreadsheet and Sheet names under "Parameters" on the right.

. Once you've checked the correct data is being returned in your SQL query, select "Database" as your destination, "Create/Replace" as your operation, and then choose the correct database you want to create/replace your new table in. Finally, enter the name of the table to be created/replaced (e.g. dummy.import_users).
+
NOTE: If your destination database is Snowflake, the table name is case-sensitive, so double-check that your destination table name is correct.

. Run the SQL and double check that your new table was created/replaced. If your source data changes often, you can set a schedule for replacing your new table (e.g. at weekly, daily, hourly intervals).

NOTE: We currently only support creating / replacing tables. If you need the ability to "upsert", please link:mailto:contact@seekwell.io[contact us] as this feature is currently in beta.
