= {seekwell} Documentation
:page-layout: home-branch-seekwell

++++
<style>
.doc-home .sidebarblock {
  background: #f1f1f1;
  border-radius: 0.75rem;
  border: 1px solid #4444;
  padding: 0.75rem 1.5rem;
  margin-top: 20px;
  margin-bottom: 20px;
  width: 96%;
}

.title {
  font-weight: 500;
  text-align: left;
}

#preamble+.sect1, .doc .sect1+.sect1 {
  margin-top: 1rem;
  margin-left: 10px;
}

.sect1 {
  margin-left: 10px;
}

.sidebarblock .title img {
  margin-bottom: -12px;
  margin-right: 5px;
}

span.image {
    vertical-align: text-bottom;
}

img {
    max-width: 95%;
    margin-top: 10px;
    margin-bottom: 10px;
}

.home .columns .box li img.inline {
    margin-top: 0;
}

ul li img {
    margin-bottom: -10px;
}

.home h1, .home h2, .home h3 {
    line-height: 1.2;
    margin: 0;
    color: #444;
    margin-top: 1rem;
}

.doc-home .columns .box {
    padding-right: 8px;
}

.doc-home .columns .box h2 {
    margin-top: 5px !important;
    margin-bottom: 5px !important;
}

#preamble+.sect1, .doc .sect1+.sect1 {
    margin-left: -1px !important;
}

</style>
++++

{seekwell} allows you to sync your data warehouse with external apps and automate your customer data workflows.


Find topics for the common {seekwell} workflows below.

[.conceal-title]
== {empty}
++++
<div class="columns">
  <div class="box">
    <h2>
      Getting started
    </h2>
    <ul>
      <li><a href="https://docs.thoughtspot.com/seekwell/latest/whitelisting-our-ip-address">Whitelist our IP address</a></li>
      <li><a href="https://docs.thoughtspot.com/seekwell/latest/local-database">Connect to a local database</a></li>
      <li><a href="https://docs.thoughtspot.com/seekwell/latest/public-blocks">Share blocks</a></li>
      <li><a href="https://docs.thoughtspot.com/seekwell/latest/granting-access-via-service-account">Grant access via Service Account</a></li>

    </ul>
    </div>
  <div class="box">
    <h2>
      SQL editor
    </h2>
    <ul>
      <li><a href="https://docs.thoughtspot.com/seekwell/latest/parameters">Parameters</a></li>
      <li><a href="https://docs.thoughtspot.com/seekwell/latest/snippets">Snippets</a></li>
      <li><a href="https://docs.thoughtspot.com/seekwell/latest/sqlite">SQLite</a></li>
      <li><a href="https://docs.thoughtspot.com/seekwell/latest/stories">Stories</a></li>
      <li><a href="https://docs.thoughtspot.com/seekwell/latest/triggers">Triggers</a></li>
      <li><a href="https://docs.thoughtspot.com/seekwell/latest/dashboards">Dashboards</a></li>
      <li><a href="https://docs.thoughtspot.com/seekwell/latest/forms">Forms</a></li>
      <li><a href="https://docs.thoughtspot.com/seekwell/latest/tables">Tables</a></li>
    <li><a href="https://docs.thoughtspot.com/seekwell/latest/pivot-tables">Pivot tables</a></li>
    </ul>
    </div>
  <div class="box">
    <h2>
      Sources
    </h2>
   <ul>
        <li><a href="https://docs.thoughtspot.com/seekwell/latest/database-source">Add a new SQL database</a></li>
<ul><li><a href="https://docs.thoughtspot.com/seekwell/latest/airtable">Airtable</a></li>
<li><a href="https://docs.thoughtspot.com/seekwell/latest/bigquery">BigQuery</a></li>
<li><a href="https://docs.thoughtspot.com/seekwell/latest/microsoft-sql-server-ms-sql">Microsoft SQL Server (MS SQL)</a></li>
<li><a href="https://docs.thoughtspot.com/seekwell/latest/connecting-to-panoply">Panoply</a></li>
<li><a href="https://docs.thoughtspot.com/seekwell/latest/connect-to-snowflake">Snowflake</a></li></ul>
<li><a href="https://docs.thoughtspot.com/seekwell/latest/query-sheets-using-sql">Query Sheets using SQL</a></li>
<li><a href="https://docs.thoughtspot.com/seekwell/latest/query-blocks">Query blocks</a></li>
<li><a href="https://docs.thoughtspot.com/seekwell/latest/query-a-csv">Query a CSV</a></li>
<li><a href="https://docs.thoughtspot.com/seekwell/latest/excel-source">Excel</a></li>
<li><a href="https://docs.thoughtspot.com/seekwell/latest/salesforce-source">Salesforce</a></li>
    </ul>
    </div>
      <div class="box">
        <h2>
          Destinations
        </h2>
        <ul>
         <li><a href="https://docs.thoughtspot.com/seekwell/latest/google-sheets">Sheets</a></li>
          <li><a href="https://docs.thoughtspot.com/seekwell/latest/excel">Excel</a></li>
       <li><a href="https://docs.thoughtspot.com/seekwell/latest/slack">Slack alerts</a></li>
       <li><a href="https://docs.thoughtspot.com/seekwell/latest/email">Email alerts</a></li>
          <li><a href="https://docs.thoughtspot.com/seekwell/latest/blocks-as-a-destination">Blocks</a></li>
          <li><a href="https://docs.thoughtspot.com/seekwell/latest/database-destination">Database</a></li>
          <li><a href="https://docs.thoughtspot.com/seekwell/latest/intercom">Intercom</a></li>
          <li><a href="https://docs.thoughtspot.com/seekwell/latest/salesforce">Salesforce</a></li>
          <li><a href="https://docs.thoughtspot.com/seekwell/latest/hubspot">HubSpot</a></li>
          <li><a href="https://docs.thoughtspot.com/seekwell/latest/zoho">Zoho</a></li>
          <li><a href="https://docs.thoughtspot.com/seekwell/latest/enter-manually">Enter manually</a></li>
          <li><a href="https://docs.thoughtspot.com/seekwell/latest/front">Front</a></li>
<li><a href="https://docs.thoughtspot.com/seekwell/latest/microsoft-teams">Microsoft Teams</a></li>
<li><a href="https://docs.thoughtspot.com/seekwell/latest/drift">Drift</a></li>
<li><a href="https://docs.thoughtspot.com/seekwell/latest/customerio">Customer.io</a></li>
<li><a href="https://docs.thoughtspot.com/seekwell/latest/active-campaign">Active Campaign</a></li>
<li><a href="https://docs.thoughtspot.com/seekwell/latest/facebook">Facebook</a></li>
<li><a href="https://docs.thoughtspot.com/seekwell/latest/close">Close</a></li>
        </ul>
        </div>
 </div>
++++
