// = Release schedule
:last_updated: 4/30/2020
:linkattrs:
:experimental:
// :page-toclevels: -1
:page-layout: default-cloud
:description:  Current schedule for ThoughtSpot Cloud cluster upgrades

// Here is the current schedule for ThoughtSpot Cloud cluster upgrades:
////
[cols="20%,40%,40%"]
|===
|Release |Development cluster upgrades|Production cluster upgrades

|9.7.0.cl
|September 26-27, 2023
|October 17-26, 2023

|9.8.0.cl
|October 26-28, 2023
|November 7-20, 2023

|9.9.0.cl
|November 16-18, 2023
|December 4-12, 2023

|Upgrade email notification
|3 days prior to upgrade
|7 days prior to upgrade
|===
////
////
[cols="15%,85%"]
|===
|Release |Upgrade dates

|9.7.0.cl
|October 17-26, 2023

|9.8.0.cl
|November 7-20, 2023

|9.9.0.cl
|December 4-12, 2023
|===

NOTE: Upgrade dates are subject to change without notice.

== Upgrade process
- New releases are deployed on a monthly basis in a phased manner across all clusters.
- Development clusters are deployed with new releases 7 to 10 days prior to production clusters to allow the release to be validated.
- For development clusters, upgrade notification emails are sent three days prior to the scheduled date of upgrade.
- For production clusters, upgrade notification emails are sent seven days prior to the scheduled date of upgrade, and reminders are sent seven days, three days, and one day prior to the scheduled date.
- Deferring an upgrade is not recommended, except for certain situations, like waiting for a fix to a critical issue encountered in your development environment. To request your upgrade to be deferred, please contact {support-url}.

== Upgrade times

Upgrades take place during off-business hours, at the following times:

- *APAC:* 10:00 AM Pacific Time (5:00 PM UTC)
- *ANZ:* 3:00 AM Pacific Time (10:00 AM UTC / 6:00 PM Singapore Time / 8:00 PM Atlantic Time / 10:00 PM New Zealand Time)
- *EMEA:* 3:00 PM Pacific Time (10:00 PM UTC)
- *US:* 8:00 PM Pacific Time (3:00 AM UTC)
////
