= ワークシート結合ルールの動作方法
:last_updated: 03/01/2024
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases: /admin/worksheets/progressive-joins.adoc
:description: The Worksheet join rule specifies when to apply joins when searching on a Worksheet.

ワークシート結合ルールを使用して、ワークシートで検索が行われたときに結合を適用するタイミングを指定します。 検索語句が追加されるたびに結合を進行的に適用するか（推奨）またはすべての検索にすべての結合を適用するかを指定できます。

== 進行的な結合の理解

しばしば、ワークシートには複数の次元テーブルと事実テーブルが含まれています。 進行的な結合を使用すると、検索に事実テーブルの用語のみが含まれる場合、検索条件を満たすすべての行を表示できます。 ただし、次元テーブルから用語を追加すると、各次元テーブルへの結合が適用されるため、表示される行の総数が減少する場合があります。 動作方法は次のとおりです:

- 結合を進行的に適用を選択する場合（ほとんどの場合に推奨）、結合は検索に含まれる列のテーブルにのみ適用されます。
- すべての結合を適用を選択する場合、検索に含まれるテーブルに関係なく、すべての可能な結合が適用されます。

Apply joinsを進行的に使用する場合、Worksheetを使用して検索する行数は、検索の一部であるテーブルに依存します。 Worksheetには、テーブルの形式で定義されたクエリの結果が含まれています。 したがって、特定の次元テーブルが検索から除外されている場合、その結合は適用されません。


== ワークシートを使用したルールベースの行レベルセキュリティ（RLS）

ルールベースのRLSでは、機密データを含むすべてのテーブルを保護する必要があります。 これを行うためには、各機密データを含む基礎テーブルに明示的な行レベルセキュリティルールを作成してアクセスを許可できます。

Worksheetの一部であるテーブルの行レベルセキュリティルールを作成する際、そのテーブルの列のみを参照することに制限されません。 ルールを作成するテーブルに結合されているテーブルからの列を指定できます。 その後、それらの上にWorksheetを作成すると、選択したWorksheet join ruleに関係なく、動作は一貫しています。 ユーザーは、検索内容に関係なく、表示すべきでないデータを見ることは決してありません。

ワークシートには、売上 ファクトテーブルと、顧客 および 製品 ディメンションが含まれており、顧客SSN および 製品コード 列で結合されています。 売上 テーブルを保護するために、顧客 列から 顧客名 を使用して行レベルのセキュリティ規則を作成できます。

== どのように chasm トラップで結合が適用されるか

ワークシートと行レベルのセキュリティを扱う際には、結合がどのように適用されるかを理解する必要があります。 特に chasm トラップスキーマではこれが重要です。 chasm トラップスキーマの場合、行レベルのセキュリティが片方のテーブルのみに設定されている場合、そのテーブルが含まれていない検索の範囲にある場合、人々は見るべきでないデータを見ることができます。 （これは chasm トラップを持っている場合、間違ったものを見せるのを防ぎます）。

chasm トラップ ワークシート の場合、進行的および非進行的な結合は適用されません。 chasm トラップスキーマ上のワークシートの結合が行レベルのセキュリティとどのように機能するかには、まったく異なる方法論があります。 その設定を無視しても安全に作業できます。

'''
> **Related information**
>
> * xref:worksheet-edit.adoc[Edit a Worksheet]
> * xref:worksheet-formula.adoc[Create a formula in a Worksheet]
> * xref:worksheet-filter.adoc[Create a Worksheet filter]
> * xref:worksheet-inclusion.adoc[Create join rule or RLS for a Worksheet]
> * xref:join-add.adoc[Create a join relationship]
> * xref:join-worksheet-edit.adoc[Modify joins between Worksheet tables]
> * xref:worksheet-delete.adoc[Delete Worksheets or tables]
> * xref:scriptability.adoc[Migrate or restore Worksheets]
> * xref:tml-worksheets.adoc[Worksheet TML specification]
