ifndef::pendo-links[]
November 2024 [label label-dep]#10.1.0.sw#
endif::[]
ifdef::pendo-links[]
[month-year-whats-new]#November 2024#
[label label-dep-whats-new]#10.1.0.sw#
endif::[]

ifndef::pendo-links[]
NOTE: Features marked as [.badge.badge-update-whats-new-beta-note]#Beta# are off by default. To enable them, contact {support-url}.
endif::[]

ifdef::pendo-links[]
NOTE: Features marked as [.badge.badge-update-whats-new-beta-note]#Beta# are off by default. To enable them, contact {support-url}.
endif::[]

[#primary-10-1-0-sw]

// Business User



// Analyst



'''
[#secondary-10-1-0-sw]
[discrete]
=== _Other features and enhancements_

// Data engineer

// TS engineer

[#tse]
[discrete]
=== ThoughtSpot Embedded

Customers licensed to embed ThoughtSpot can use ThoughtSpot Embedded features and the Visual Embed SDK.

To enable ThoughtSpot Embedded on your cluster, contact {support-url}.

For new features and enhancements introduced in this release for ThoughtSpot Embedded, see https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].