= 10.1.0.sw Release Notes
:experimental:
:last_updated: 10/26/23
:linkattrs:
:page-aliases: /release/notes.adoc
:description: These release notes include information about new and enhanced features.

++++
<style>
.badge-update-whats-new-beta {
  font-style: normal !important;
  top: -0.03rem !important;
}

</style>
++++

ThoughtSpot version 10.1.0.sw is now available.

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

For a complete list of issues that we fixed in this release, see xref:fixed.adoc#releases-10-1-x[Fixed issues].

* <<new-10-1-0,10.1.0.sw New Features and Functionality>>
* <<upgrade-paths,Supported Upgrade Paths>>

[#new-10-1-0]
== 10.1.0.sw New Features and Functionality


* <<analyst-10-1-0-sw,For the Analyst>>
* <<business-user-10-1-0-sw,For the Business User>>
* <<data-engineer-10-1-0-sw,For the Data Engineer>>
* <<it-ops-engineer-10-1-0-sw,For the IT Ops Engineer>>
* <<developer-10-1-0-sw,For the Developer>>

[#analyst-10-1-0-sw]
=== For the Analyst

// Naomi – SCAL-181312. documentation JIRA scal-201645.
Remember personalized columns in change analysis::
Personalized columns are now available to all users and on by default. Users with edit permissions on a Liveboard can set their preferred attribute columns through the change analysis window and select *Apply to all users* to keep those selections for any subsequent change analysis calculations on that Liveboard. Individual users can still override these preferences for their own calculations. +
For more information, see
xref:spotiq-change.adoc#remember-personalized[Remember personalized columns].

// Naomi -- scal-201040
Renaming columns::
You can now rename columns in an Answer and see the new name reflected on the table header, tooltips, legend, and chart configuration menu. Changes made to an Answer are not reflected in the underlying Worksheet. For more information, see xref:chart-column-axis-rename.adoc#column-rename[Rename a table column].

Language updates::
// Naomi. epic: SCAL-181448. doc: SCAL-199383 (approved). epic: SCAL-159833. doc: SCAL-208059 (approved)
// PM: Aashna
ThoughtSpot now supports xref:keywords-ko-KR.adoc[Korean], and we've also added synonyms for date and time based keywords in xref:keywords-de-DE.adoc[German] and xref:keywords-fr-FR.adoc[French] for a more accurate experience.

[#business-user-10-1-0-sw]
=== For the Business User

Redesigned home page [.badge.badge-early-access-relnotes]#Early Access#::
// Mark. doc jira: SCAL-151210
In this release, you can try our redesigned and customizable home page, where you can ask natural-language questions with Sage, view your watchlist, favorites, library of Answers and Liveboards, and more. With the new left-hand navigation, you can go directly to your Liveboards, Answers, SpotIQ Analysis, and Monitor Subscriptions.
+
This new home page experience is disabled by default. Contact your ThoughtSpot administrator to enable this feature for your cluster. After that, open your user profile, and in the _Experience_ section, set the _Navigation and Homepage_ to *New experience*. Note that this setting also enables persona-based navigation. For more information, see xref:thoughtspot-homepage.adoc[].

New persona-based navigation [.badge.badge-early-access-relnotes]#Early Access#::
// Mark. Doc jira: SCAL-175398
In this release, you can try our completely redesigned navigation experience organized by persona. The new app switcher allows business users, analysts, data engineers, administrators, and developers to work in separate contextual sections designed specifically for their needs. In addition, each app has left-hand navigation to create better consistency and ease of use for users switching between the different apps.
+
This new navigation experience is disabled by default. Contact your ThoughtSpot administrator to enable this feature for your cluster. After that, open your user profile, and in the _Experience_ section, set the _Navigation and Homepage_ to *New experience*. Note that this setting also enables the redesigned home page. For more information, see xref:thoughtspot-homepage.adoc[].

// Naomi -- scal-201035
Null and missing values in charts::
You can now choose how null and missing values appear in line, column, and bar charts in ThoughtSpot. Null and missing values appear as bars of 1 pixel width on bar and column charts. You can choose whether to display null date values as zero values, line breaks, or an average of proximate values on a line chart. Rather than showing a sharp decline to zero every time there is null or missing data on your line chart, you can see the missing values represented as line breaks or averages of the closest values instead. For more information, see
xref:chart-null-missing.adoc[Null and missing values in charts].

// Naomi – JIRA SCAL-214756
Semi-additive measures with first and last values:: Semi-additive measures with first and last values are now available to all users and on by default. A semi-additive measure, also known as snapshot data, is a measure that is usually aggregated for all attributes except for date and time. For certain measures, like inventory, you want to know what the value was at the beginning or end of a period. In that case, you can use the `last_value` function to find the inventory at the end of a month, rather than aggregating all values over the month. Similarly, you can use the `first_value` function to find out your stock at the beginning of a month.
+
For more information, see
xref:semi-additive-measures.adoc[Semi-additive measures with `first_value` and `last_value` functions] and xref:semi-additive-modeling.adoc[Modeling data for semi-additive measures].

// Naomi -- JIRA SCAL-201298
Keywords "of" and "percentage of":: The "of" and "percentage of" keywords are now on by default and available to all users. You can use the "of" and "percentage of" keywords to answer questions related to mix, contribution, share of, percentage, and total ratios. These keywords help answer questions such as, "What is the share of a certain store’s sales as a percentage of the regional whole?" To try out this feature, enter a search phrase in the search bar containing the keyword, such as `sales percentage of store region`, and press *Go*.
+
For more information, see xref:formulas-keywords.adoc[Keywords: Of and Percentage of].

Drill down in change analysis::
// Naomi – SCAL-180942. doc: SCAL-205576 (approved)
// PM: Vikas, Rahul PJP
Drill down in change analysis is now on by default and available to all users. You can now drill down on specific columns in change analysis, in order to identify change drivers within your data. For example, if you run an analysis on sales monthly and find out that the 'jacket' item type changed the most, you can easily drill down on jacket sales and identify which region contributed the most to the change in sales. For more information, see xref:spotiq-change.adoc#iterative[Iterative change analysis].


// Naomi. SCAL-178764. docs JIRA SCAL-204357. release notes only.
Error message improvements:: We have improved the error messages for CSV upload and custom calendar.

[#data-engineer-10-1-0-sw]
=== For the Data Engineer

// Mark -- Jira: SCAL-196890

Version control for Liveboards and Answers::
Version control for Liveboards and Answers is available to all users. Now teams of analysts can more easily collaborate on content development of Liveboards and Answers. You can enable version control on specific Liveboards and Answers. With version control enabled, every time you save the Liveboard or Answer, a new version is created and stored. You can browse the version history in ThoughtSpot and restore any saved versions whenever you need to. To enable this feature, contact your administrator. For more information, see xref:liveboards.adoc#version-history[Liveboards] and xref:answers.adoc#version-history[Answers].

// Naomi -- SCAL-164290, SCAL-201306
Ts_Groups system variable::
ThoughtSpot now supports the `ts_groups` system variable in Answer and Worksheet formulas. You can use the `ts_groups` variable for data masking, or deciding whether to display the value of a column to a user based on their group membership. For more information, see xref:data-masking.adoc[].

// Naomi - JIRA: SCAL-209029. Confirm if we support OAuth for Starburst in Software
OAuth for Starburst using Proof Key for Code Exchange (PKCE):: We now support xref:connections-starburst-add.adoc[OAuth with PKCE for Starburst].

// Naomi – SCAL-191462, documentation jira scal-196178
Snowflake secondary role configuration for External OAuth::
ThoughtSpot now supports secondary role configuration when you create a Snowflake connection using External OAuth. When you set secondary roles to `ALL`, you can access all tables that any single role has access to and combine them in a single SQL query without having to switch roles.
+
For more information on primary and secondary roles, see link:https://docs.snowflake.com/en/user-guide/security-access-control-overview#enforcement-model-with-primary-role-and-secondary-roles[Enforcement model with primary role and secondary roles^] and xref:connections-snowflake-add.adoc#secondary[Add a Snowflake connection].

// Mark - SCAL-205579

Answer data panel enhancements::
Now in the new Answer data panel, you can filter as you hover on a column, _By category_ grouping by default, and display the information panel when you click a column.

// Mark -- Jira: SCAL-196890

Enabling GIT integration for version control of Liveboards and Answers::
Administrators can now enable version control of Liveboards and Answers. You enable version control for your ThoughtSpot Org by connecting it to a Github repository. Once enabled for the Org, version control can be enabled individually for any Liveboard or Answer. Each time a user saves changes, a new version of the Liveboard or Answer is created and stored in your Github repository. Users can easily browse and restore an older version from the Liveboard or Answer itself. For more information, see xref:git-version-control.adoc[Version control for Liveboards and Answers].

[#it-ops-engineer-10-1-0-sw]
=== For the IT Ops Engineer


[#developer-10-1-0-sw]
=== For the Developer

Customers licensed to embed ThoughtSpot can use ThoughtSpot Embedded features and Visual Embed SDK.

To enable ThoughtSpot Embedded on your cluster, contact {support-url}.

For information about ThoughtSpot Embedded, refer to  link:https://developers.thoughtspot.com/docs[ThoughtSpot Embedded Documentation, window=_blank].

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 10.1.0.sw release directly:

* 9.8.0.sw to 10.1.0.sw
* 9.5.0.sw to 10.1.0.sw

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

First, upgrade to version 9.8.0.sw or 9.5.0.sw, and then to the 10.1.0.sw release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
