= 10.1.0.sw Release Notes
:experimental:
:last_updated: 10/26/23
:linkattrs:
:page-aliases: /release/notes.adoc
:description: These release notes include information about new and enhanced features.

++++
<style>
.badge-update-whats-new-beta {
  font-style: normal !important;
  top: -0.03rem !important;
}

</style>
++++

ThoughtSpot version 10.1.0.sw is now available.

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

For a complete list of issues that we fixed in this release, see xref:fixed.adoc#releases-9-8-x[Fixed issues].

* <<new-9-8-0,9.8.0.sw New Features and Functionality>>
* <<upgrade-paths,Supported Upgrade Paths>>

[#new-10-1-0]
== 10.1.0.sw New Features and Functionality


* <<analyst-10-1-0-sw,For the Analyst>>
* <<business-user-10-1-0-sw,For the Business User>>
* <<data-engineer-10-1-0-sw,For the Data Engineer>>
* <<it-ops-engineer-10-1-0-sw,For the IT Ops Engineer>>
* <<developer-10-1-0-sw,For the Developer>>

[#analyst-10-1-0-sw]
=== For the Analyst



[#business-user-10-1-0-sw]
=== For the Business User

// Naomi – JIRA SCAL-214756
Semi-additive measures with first and last values:: Semi-additive measures with first and last values are now available to all users and on by default. A semi-additive measure, also known as snapshot data, is a measure that is usually aggregated for all attributes except for date and time. For certain measures, like inventory, you want to know what the value was at the beginning or end of a period. In that case, you can use the `last_value` function to find the inventory at the end of a month, rather than aggregating all values over the month. Similarly, you can use the `first_value` function to find out your stock at the beginning of a month.
+
For more information, see
xref:semi-additive-measures.adoc[Semi-additive measures with `first_value` and `last_value` functions] and xref:semi-additive-modeling.adoc[Modeling data for semi-additive measures].

// Naomi -- JIRA SCAL-201298
Keywords "of" and "percentage of":: The "of" and "percentage of" keywords are now on by default and available to all users. You can use the "of" and "percentage of" keywords to answer questions related to mix, contribution, share of, percentage, and total ratios. These keywords help answer questions such as, "What is the share of a certain store’s sales as a percentage of the regional whole?" To try out this feature, enter a search phrase in the search bar containing the keyword, such as `sales percentage of store region`, and press *Go*.
+
For more information, see xref:formulas-keywords.adoc[Keywords: Of and Percentage of].

Drill down in change analysis::
// Naomi – SCAL-180942. doc: SCAL-205576 (approved)
// PM: Vikas, Rahul PJP
Drill down in change analysis is now on by default and available to all users. You can now drill down on specific columns in change analysis, in order to identify change drivers within your data. For example, if you run an analysis on sales monthly and find out that the 'jacket' item type changed the most, you can easily drill down on jacket sales and identify which region contributed the most to the change in sales. For more information, see xref:spotiq-change.adoc#iterative[Iterative change analysis].

// Naomi – SCAL-181312. documentation JIRA scal-201645.
Remember personalized columns in change analysis::
Personalized columns are now available to all users and on by default. Users with edit permissions on a Liveboard can set their preferred attribute columns through the change analysis window and select *Apply to all users* to keep those selections for any subsequent change analysis calculations on that Liveboard. Individual users can still override these preferences for their own calculations. +
For more information, see
xref:spotiq-change.adoc#remember-personalized[Remember personalized columns].

// Naomi -- SCAL-164290, SCAL-201306
Ts_Groups system variable::
ThoughtSpot now supports the `ts_groups` system variable in Answer and Worksheet formulas. You can use the `ts_groups` variable for data masking, or deciding whether to display the value of a column to a user based on their group membership.

Language updates::
// Naomi. epic: SCAL-181448. doc: SCAL-199383 (approved). epic: SCAL-159833. doc: SCAL-208059 (approved)
// PM: Aashna
ThoughtSpot now supports xref:keywords-ko-KR.adoc[Korean], and we've also added synonyms for date and time based keywords in xref:keywords-de-DE.adoc[German] and xref:keywords-fr-FR.adoc[French] for a more accurate experience.

// Naomi. SCAL-178764. docs JIRA SCAL-204357
Error message improvements:: We have improved the error messages for CSV upload and custom calendar.

[#data-engineer-10-1-0-sw]
=== For the Data Engineer

// Naomi - JIRA: SCAL-209029
OAuth for Starburst using Proof Key for Code Exchange (PKCE):: We now support xref:connections-starburst-add.adoc[OAuth with PKCE for Starburst].

// Naomi – SCAL-191462, documentation jira scal-196178
Snowflake secondary role configuration for External OAuth::
ThoughtSpot now supports secondary role configuration when you create a Snowflake connection using External OAuth. When you set secondary roles to `ALL`, you can access all tables that any single role has access to and combine them in a single SQL query without having to switch roles.
+
For more information on primary and secondary roles, see link:https://docs.snowflake.com/en/user-guide/security-access-control-overview#enforcement-model-with-primary-role-and-secondary-roles[Enforcement model with primary role and secondary roles^] and xref:connections-snowflake-add.adoc#secondary[Add a Snowflake connection].

[#it-ops-engineer-10-1-0-sw]
=== For the IT Ops Engineer


[#developer-10-1-0-sw]
=== For the Developer

Customers licensed to embed ThoughtSpot can use ThoughtSpot Embedded features and Visual Embed SDK.

To enable ThoughtSpot Embedded on your cluster, contact {support-url}.

For information about ThoughtSpot Embedded, refer to  link:https://developers.thoughtspot.com/docs[ThoughtSpot Embedded Documentation, window=_blank].

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 10.1.0.sw release directly:

* 9.8.0.sw to 10.1.0.sw
* 9.5.0.sw to 10.1.0.sw

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

First, upgrade to version 9.8.0.sw or 9.5.0.sw, and then to the 10.1.0.sw release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
