= ThoughtSpot mobile Liveboards
:last_updated: 6/26/2024
:linkattrs:
:experimental:
:page-aliases:
:description: ThoughtSpot mobile Liveboards.

Liveboards are the ThoughtSpot term for a dashboard. They group and manage related search result visuals.

What are Liveboards::
Liveboards act like live dashboards. They are collections of your related Answers, in the form of charts and tables, and your headline metrics.
Liveboard authors can pin charts and tables to any Liveboard that they create or edit. Liveboards can be shared with view privileges to mobile users.

NOTE: ThoughtSpot mobile users can view but not edit Liveboards in the mobile app.

Search Liveboards::
ThoughtSpot mobile allow you to search Liveboards that have been shared with you to ge the information that you need. Search Liveboards supports users who are not yet familiar with the data in their organization.

How to search Liveboards::
. To search Liveboards, select the *Liveboards* tab.
. You can choose to search:
.. Only the Liveboards that you have marked as favorites by selecting *Favorites*.
.. All Liveboards that you have access to by selecting *All*.
.. Only your own Liveboards by selecting *Yours*.
. Enter your search terms in the *Search Liveboards* field, and click *Return*.

The Liveboards matching your search criteria are displayed in the app.